// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sat Jul 11 02:18:15 2026

top top_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.reset(reset_sig) ,	// input  reset_sig
	.hash_register(hash_register_sig) ,	// output [P-1:0] hash_register_sig
	.batch_ready(batch_ready_sig) ,	// output  batch_ready_sig
	.done(done_sig) 	// output  done_sig
);

defparam top_inst.N = 2000;
defparam top_inst.W = 64;
defparam top_inst.P = 300;
defparam top_inst.L = 600;
defparam top_inst.AES_CYCLES = 20;
defparam top_inst.SEED_KEY = 'b00101011011111100001010100010110001010001010111011010010101001101010101111110111000101011000100000001001110011110100111100111100;
defparam top_inst.SEED_NONCE = 'b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;
