// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: rom_key.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// ************************************************************


//Copyright (C) 2018  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on

module rom_key #(
    parameter DATA_BITS = 64,
    parameter ADDR_BITS = 5,
    parameter DEPTH     = 32
)(
    input  wire [ADDR_BITS-1:0] address,
    input  wire                 clock,
    output wire [DATA_BITS-1:0] q
);

    wire       q_b_unused;
    wire [2:0] eccstatus_unused;

    altsyncram #(
        .operation_mode         ("ROM"),
        .intended_device_family ("Cyclone IV E"),
        .width_a                (DATA_BITS),
        .widthad_a              (ADDR_BITS),
        .numwords_a             (DEPTH),
        .outdata_reg_a          ("UNREGISTERED"),
        .address_aclr_a         ("NONE"),
        .outdata_aclr_a         ("NONE"),
        .init_file              ("key.mif"),
        .lpm_type               ("altsyncram")
    ) altsyncram_component (
        .clock0         (clock),
        .address_a      (address),
        .data_a         ({DATA_BITS{1'b0}}),
        .wren_a         (1'b0),
        .q_a            (q),

        .wren_b         (1'b0),
        .rden_a         (1'b1),
        .rden_b         (1'b0),
        .data_b         (1'b0),
        .address_b      (1'b0),
        .clock1         (1'b0),
        .clocken0       (1'b1),
        .clocken1       (1'b1),
        .clocken2       (1'b1),
        .clocken3       (1'b1),
        .aclr0          (1'b0),
        .aclr1          (1'b0),
        .byteena_a      (1'b1),
        .byteena_b      (1'b1),
        .addressstall_a (1'b0),
        .addressstall_b (1'b0),
        .q_b            (q_b_unused),
        .eccstatus      (eccstatus_unused)
    );

endmodule
